### ISSUE TITLE
api/chatroom API 500에러 발생

### ISSUE THREAD

**Issue by SkyBelll** [Bros4Kkun/Back-end#102]
**버그 설명**
- api/chatroom 접근 시 에러코드 500로 접근 불가

**버그 발생 절차**

**기대했던 동작**

**Comment by TaegyunWoo** [comment]
아마 db 관련한 문제일 것 같기는 한데, 확인해볼개요!

**Comment by TaegyunWoo** [comment]
### 오류 발생 이유
- 포인트 제도를 도입하고자 DB를 변경함.
- **하지만 변경된 DB에 맞춰 수정한 코드를 main 브랜치에 merge 하지 않아 발생한 문제**
